import streamlit as st
import pandas as pd
import os
import re
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
REPORTS_DIR = BASE_DIR / "reports"

REPORTS_FOLDER = REPORTS_DIR / "employee_reports"
HIGH_RISK_PATH = REPORTS_DIR / "high_risk_employees.csv"

# =========================================================
# PATHS
# =========================================================
REPORTS_FOLDER = r"C:\Users\hp\Desktop\Projects\HR-People-Analytics\reports\employee_reports"
HIGH_RISK_PATH = r"C:\Users\hp\Desktop\Projects\HR-People-Analytics\reports\high_risk_employees.csv"


# =========================================================
# UI HELPERS
# =========================================================
def premium_card(title, value, subtitle="", color1="#7C3AED", color2="#2563EB"):
    st.markdown(
        f"""
        <div style="
            background: linear-gradient(135deg, {color1}22, {color2}18);
            border: 1px solid rgba(255,255,255,0.08);
            border-radius: 18px;
            padding: 18px 20px;
            min-height: 120px;
            box-shadow: 0 10px 24px rgba(0,0,0,0.16);
        ">
            <div style="font-size: 0.95rem; color: #CBD5E1; margin-bottom: 8px;">{title}</div>
            <div style="font-size: 2rem; font-weight: 800; color: #F8FAFC;">{value}</div>
            <div style="font-size: 0.85rem; color: #94A3B8; margin-top: 8px; line-height: 1.5;">{subtitle}</div>
        </div>
        """,
        unsafe_allow_html=True
    )


def info_panel(title, body, emoji="📌", bg="rgba(255,255,255,0.03)", border="rgba(255,255,255,0.08)"):
    st.markdown(
        f"""
        <div style="
            background: {bg};
            border: 1px solid {border};
            border-radius: 18px;
            padding: 18px;
            min-height: 145px;
        ">
            <div style="font-size: 1rem; font-weight: 700; color: #F8FAFC; margin-bottom: 10px;">
                {emoji} {title}
            </div>
            <div style="color: #CBD5E1; line-height: 1.7; font-size: 0.95rem;">
                {body}
            </div>
        </div>
        """,
        unsafe_allow_html=True
    )


# =========================================================
# HELPERS
# =========================================================
def get_report_files():
    if not os.path.exists(REPORTS_FOLDER):
        return []
    return sorted([f for f in os.listdir(REPORTS_FOLDER) if f.endswith(".txt")])


def extract_employee_number(report_filename):
    """
    Example:
    employee_0.txt -> 0
    employee_25.txt -> 25
    """
    match = re.search(r"employee_(\d+)\.txt", report_filename)
    if match:
        return int(match.group(1))
    return None


def load_report_text(report_filename):
    report_path = os.path.join(REPORTS_FOLDER, report_filename)
    if not os.path.exists(report_path):
        return None

    with open(report_path, "r", encoding="utf-8") as f:
        return f.read()


def load_employee_metadata(employee_number):
    """
    If high_risk_employees.csv exists and employee number maps to a row index,
    return employee metadata from that row.
    """
    if not os.path.exists(HIGH_RISK_PATH):
        return None

    try:
        df = pd.read_csv(HIGH_RISK_PATH)

        if employee_number is None:
            return None

        if employee_number < 0 or employee_number >= len(df):
            return None

        row = df.iloc[employee_number]
        return row
    except:
        return None


def safe_get(row, col_name, default="N/A"):
    try:
        if row is None:
            return default
        value = row[col_name]
        if pd.isna(value):
            return default
        return value
    except:
        return default


# =========================================================
# MAIN PAGE
# =========================================================
def show_employee_reports():
    st.markdown("""
    <div style="
        background: linear-gradient(135deg, rgba(124,58,237,0.20), rgba(37,99,235,0.12));
        border: 1px solid rgba(255,255,255,0.08);
        border-radius: 24px;
        padding: 26px 28px;
        margin-bottom: 22px;
        box-shadow: 0 12px 32px rgba(0,0,0,0.18);
    ">
        <div style="font-size: 2.2rem; font-weight: 800; color: #F8FAFC; margin-bottom: 10px;">
            📝 Employee Reports
        </div>
        <div style="font-size: 1rem; color: #CBD5E1; line-height: 1.8; max-width: 1100px;">
            Explore AI-generated employee attrition risk reports, review workforce risk context,
            and inspect individual employee-level HR insights generated by the People Analytics system.
        </div>
    </div>
    """, unsafe_allow_html=True)

    report_files = get_report_files()

    if not report_files:
        st.warning("No employee report files found in reports/employee_reports.")
        return

    # -----------------------------------------------------
    # Report selector
    # -----------------------------------------------------
    st.markdown("## Select Employee Report")

    top_left, top_right = st.columns([1, 2])

    with top_left:
        selected_report = st.selectbox(
            "Choose Report File",
            report_files
        )

    employee_number = extract_employee_number(selected_report)
    employee_row = load_employee_metadata(employee_number)
    report_text = load_report_text(selected_report)

    with top_right:
        st.markdown(
            f"""
            <div style="
                background: rgba(255,255,255,0.03);
                border: 1px solid rgba(255,255,255,0.08);
                border-radius: 18px;
                padding: 16px 18px;
                margin-top: 28px;
            ">
                <div style="color:#F8FAFC; font-size:1rem; font-weight:700; margin-bottom:8px;">
                    Selected Report
                </div>
                <div style="color:#CBD5E1; line-height:1.7;">
                    <b>File:</b> {selected_report}<br>
                    <b>Employee Index:</b> {employee_number if employee_number is not None else "N/A"}
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    st.markdown("<div style='height: 18px;'></div>", unsafe_allow_html=True)

    # -----------------------------------------------------
    # Employee summary cards
    # -----------------------------------------------------
    st.markdown("## Employee Snapshot")

    emp_id = safe_get(employee_row, "EmployeeNumber", employee_number if employee_number is not None else "N/A")
    department = safe_get(employee_row, "Department")
    job_role = safe_get(employee_row, "JobRole")
    risk_level = safe_get(employee_row, "Risk Level")
    overtime = safe_get(employee_row, "OverTime")

    c1, c2, c3, c4 = st.columns(4)

    with c1:
        premium_card(
            "Employee ID",
            emp_id,
            "Employee reference identifier",
            "#7C3AED",
            "#2563EB"
        )

    with c2:
        premium_card(
            "Department",
            department,
            "Department associated with the selected employee",
            "#2563EB",
            "#06B6D4"
        )

    with c3:
        premium_card(
            "Job Role",
            job_role,
            "Current employee role in the dataset",
            "#059669",
            "#10B981"
        )

    with c4:
        premium_card(
            "Risk Level",
            risk_level,
            "Attrition risk level from model output",
            "#DC2626",
            "#F97316"
        )

    st.markdown("<div style='height: 18px;'></div>", unsafe_allow_html=True)

    # -----------------------------------------------------
    # Employee context panels
    # -----------------------------------------------------
    st.markdown("## Employee Risk Context")

    left, right = st.columns(2)

    with left:
        years_at_company = safe_get(employee_row, "YearsAtCompany")
        monthly_income = safe_get(employee_row, "MonthlyIncome")
        age = safe_get(employee_row, "Age")

        info_panel(
            "Workforce Profile",
            f"""
            <b>Age:</b> {age}<br>
            <b>Years At Company:</b> {years_at_company}<br>
            <b>Monthly Income:</b> {monthly_income}
            """,
            emoji="👤",
            bg="rgba(59,130,246,0.10)",
            border="rgba(59,130,246,0.22)"
        )

    with right:
        job_satisfaction = safe_get(employee_row, "JobSatisfaction")
        env_satisfaction = safe_get(employee_row, "EnvironmentSatisfaction")
        work_life_balance = safe_get(employee_row, "WorkLifeBalance")

        info_panel(
            "Engagement & Work Conditions",
            f"""
            <b>OverTime:</b> {overtime}<br>
            <b>Job Satisfaction:</b> {job_satisfaction}<br>
            <b>Environment Satisfaction:</b> {env_satisfaction}<br>
            <b>Work-Life Balance:</b> {work_life_balance}
            """,
            emoji="📊",
            bg="rgba(16,185,129,0.10)",
            border="rgba(16,185,129,0.22)"
        )

    st.markdown("<div style='height: 18px;'></div>", unsafe_allow_html=True)

    # -----------------------------------------------------
    # Full employee row (optional metadata table)
    # -----------------------------------------------------
    if employee_row is not None:
        st.markdown("## Employee Metadata")
        employee_df = pd.DataFrame(employee_row).reset_index()
        employee_df.columns = ["Field", "Value"]
        st.dataframe(employee_df, use_container_width=True)

    st.markdown("<div style='height: 18px;'></div>", unsafe_allow_html=True)

    # -----------------------------------------------------
    # AI Report
    # -----------------------------------------------------
    st.markdown("## AI Employee Risk Report")

    if report_text:
        st.markdown(
            f"""
            <div style="
                background: rgba(255,255,255,0.03);
                border: 1px solid rgba(255,255,255,0.08);
                border-radius: 20px;
                padding: 22px;
                line-height: 1.8;
                color: #E2E8F0;
                box-shadow: 0 10px 30px rgba(0,0,0,0.12);
                white-space: pre-wrap;
            ">
                {report_text}
            </div>
            """,
            unsafe_allow_html=True
        )

        st.download_button(
            label="Download Employee Report",
            data=report_text,
            file_name=selected_report,
            mime="text/plain"
        )
    else:
        st.warning("Could not load the selected employee report.")

    st.markdown("<div style='height: 12px;'></div>", unsafe_allow_html=True)
    st.caption("Developed by Rudra Sharad Mhaske")